export const ANIMAL_ACTION = {
    REQUEST: 'ANIMAL_REQUEST',
    SUCCESS: 'ANIMAL_SUCCESS',
    FAILURE: 'ANIMAL_FAILURE'
}

export const ALL_ANIMAL_ACTION = {
    REQUEST: 'ALL_ANIMAL_REQUEST',
    SUCCESS: 'ALL_ANIMAL_SUCCESS',
    FAILURE: 'ALL_ANIMAL_FAILURE'
}

export const ALL_FOODS_ACTION = {
    REQUEST: 'ALL_FOODS_REQUEST',
    SUCCESS: 'ALL_FOODS_SUCCESS',
    FAILURE: 'ALL_FOODS_FAILURE'
}

export const FOOD_ACTION = {
    REQUEST: 'FOOD_REQUEST',
    SUCCESS: 'FOOD_SUCCESS',
    FAILURE: 'FOOD_FAILURE'
}

export const FURNITURE_ACTION = {
    REQUEST: 'FURNITURE_REQUEST',
    SUCCESS: 'FURNITURE_SUCCESS',
    FAILURE: 'FURNITURE_FAILURE'
}

export const ALL_FURNITURE_ACTION = {
    REQUEST: 'ALL_FURNITURE_REQUEST',
    SUCCESS: 'ALL_FURNITURE_SUCCESS',
    FAILURE: 'ALL_FURNITURE_FAILURE'
}

export const NATURE_ACTION = {
    REQUEST: 'NATURE_REQUEST',
    SUCCESS: 'NATURE_SUCCESS',
    FAILURE: 'NATURE_FAILURE'
}

export const ALL_NATURE_ACTION = {
    REQUEST: 'ALL_NATURE_REQUEST',
    SUCCESS: 'ALL_NATURE_SUCCESS',
    FAILURE: 'ALL_NATURE_FAILURE'
}

export const TECH_ACTION = {
    REQUEST: 'TECH_REQUEST',
    SUCCESS: 'TECH_SUCCESS',
    FAILURE: 'TECH_FAILURE'
}

export const ALL_TECH_ACTION = {
    REQUEST: 'ALL_TECH_REQUEST',
    SUCCESS: 'ALL_TECH_SUCCESS',
    FAILURE: 'ALL_TECH_FAILURE'
}

export const TRANSPORT_ACTION = {
    REQUEST: 'TRANSPORT_REQUEST',
    SUCCESS: 'TRANSPORT_SUCCESS',
    FAILURE: 'TRANSPORT_FAILURE'
}

export const ALL_TRANSPORT_ACTION = {
    REQUEST: 'ALL_TRANSPORT_REQUEST',
    SUCCESS: 'ALL_TRANSPORT_SUCCESS',
    FAILURE: 'ALL_TRANSPORT_FAILURE'
}

